{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--90c4fce2-89d8-4fda-8979-5b7922123532",
    "created": "2020-05-26T20:29:27.026163Z",
    "modified": "2020-05-26T20:29:27.026163Z",
    "name": "CVE-2016-9949",
    "description": "An issue was discovered in Apport before 2.20.4. In apport/ui.py, Apport reads the CrashDB field and it then evaluates the field as Python code if it begins with a \"\"{\"\". This allows remote attackers to execute arbitrary Python code."
}