{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--75e42dfe-e012-4a9c-a8fe-bef092e6a6fc",
    "created": "2020-05-26T20:29:59.76594Z",
    "modified": "2020-05-26T20:29:59.76594Z",
    "name": "CVE-2019-12903",
    "description": "Pydio Cells before 1.5.0, when supplied with a Name field in an unexpected Unicode format, fails to handle this and includes the database column/table name as pert of the error message, exposing sensitive information."
}