{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--d34b4db8-744d-4eba-8bff-f0ca5a108b52",
    "created": "2020-05-26T20:30:02.605337Z",
    "modified": "2020-05-26T20:30:02.605337Z",
    "name": "CVE-2019-16729",
    "description": "pam-python before 1.0.7-1 has an issue in regard to the default environment variable handling of Python, which could allow for local root escalation in certain PAM setups."
}