{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--f413af2a-cb00-402e-9d18-ce88a0ee33a5",
    "created": "2020-05-26T20:30:04.213835Z",
    "modified": "2020-05-26T20:30:04.213835Z",
    "name": "CVE-2019-19588",
    "description": "The validators package 0.12.2 through 0.12.5 for Python enters an infinite loop when validators.domain is called with a crafted domain string. This is fixed in 0.12.6."
}