{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--828b002c-eea3-4e5c-9623-a1eb8cb7c22b",
    "created": "2020-05-26T20:30:02.292561Z",
    "modified": "2020-05-26T20:30:02.292561Z",
    "name": "CVE-2019-16224",
    "description": "An issue was discovered in py-lmdb 0.97. For certain values of md_flags, mdb_node_add does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
}