{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--9ee909a2-bdf1-4741-b247-1ab03908dcce",
    "created": "2020-05-26T20:30:04.487823Z",
    "modified": "2020-05-26T20:30:04.487823Z",
    "name": "CVE-2019-19950",
    "description": "In GraphicsMagick 1.4 snapshot-20190403 Q8, there is a use-after-free in ThrowException and ThrowLoggedException of magick/error.c."
}