{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--0a9d8937-e55c-442d-b576-77669dcb929c",
    "created": "2020-05-26T20:30:04.013278Z",
    "modified": "2020-05-26T20:30:04.013278Z",
    "name": "CVE-2019-19275",
    "description": "typed_ast 1.3.0 and 1.3.1 has an ast_for_arguments out-of-bounds read. An attacker with the ability to cause a Python interpreter to parse Python source (but not necessarily execute it) may be able to crash the interpreter process. This could be a concern, for example, in a web-based service that parses (but does not execute) Python code. (This issue also affected certain Python 3.8.0-alpha prereleases.)"
}