{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--d659f41e-037a-4363-8e70-911b4e6a6db0",
    "created": "2020-05-26T20:29:14.491403Z",
    "modified": "2020-05-26T20:29:14.491403Z",
    "name": "CVE-2015-5145",
    "description": "validators.URLValidator in Django 1.8.x before 1.8.3 allows remote attackers to cause a denial of service (CPU consumption) via unspecified vectors."
}