{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--928f0b14-2cac-454b-9470-6819384c119f",
    "created": "2020-05-26T20:30:06.740752Z",
    "modified": "2020-05-26T20:30:06.740752Z",
    "name": "CVE-2019-5010",
    "description": "An exploitable denial-of-service vulnerability exists in the X509 certificate parser of Python.org Python 2.7.11 / 3.6.6. A specially crafted X509 certificate can cause a NULL pointer dereference, resulting in a denial of service. An attacker can initiate or accept TLS connections using crafted certificates to trigger this vulnerability."
}