{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--798384a9-c741-4c1e-859c-206dc703cc58",
    "created": "2020-05-26T20:30:02.295956Z",
    "modified": "2020-05-26T20:30:02.295956Z",
    "name": "CVE-2019-16228",
    "description": "An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
}