{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--02d2192d-891f-4699-8a02-29ebe7b7a33e",
    "created": "2020-05-26T20:30:10.047808Z",
    "modified": "2020-05-26T20:30:10.047808Z",
    "name": "CVE-2019-9948",
    "description": "urllib in Python 2.x through 2.7.16 supports the local_file: scheme, which makes it easier for remote attackers to bypass protection mechanisms that blacklist file: URIs, as demonstrated by triggering a urllib.urlopen('local_file:///etc/passwd') call."
}