{
    "type": "bundle",
    "id": "bundle--fe8a825c-9bb6-403c-9a59-582b33bfd5c8",
    "spec_version": "2.0",
    "objects": [
        {
            "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
            "object_marking_refs": [
                "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
            ],
            "source_ref": "malware--d9f7383c-95ec-4080-bbce-121c9384457b",
            "target_ref": "attack-pattern--f5d8eed6-48a9-4cdf-a3d7-d1ffa99c3d2a",
            "external_references": [
                {
                    "source_name": "McAfee Maze March 2020",
                    "url": "https://www.mcafee.com/blogs/other-blogs/mcafee-labs/ransomware-maze/",
                    "description": "Mundo, A. (2020, March 26). Ransomware Maze. Retrieved May 18, 2020."
                }
            ],
            "description": "[MAZE](https://attack.mitre.org/software/S0449) has attempted to delete the shadow volumes of infected machines, once before and once after the encryption process.(Citation: McAfee Maze March 2020)",
            "relationship_type": "uses",
            "id": "relationship--ea32ebd2-9827-43ec-a3d3-f0148fee8ed8",
            "type": "relationship",
            "modified": "2020-06-24T01:40:07.449Z",
            "created": "2020-05-18T17:31:39.474Z"
        }
    ]
}